from src.models.product import ProductIn
from src.models.product import TypeEnum

# OK!!

chopps: list[ProductIn] = [
    ProductIn(
        name="Chopp SUD PREMIUM LAGER puro malte 500ml",
        description="""A primeira Pilsen artesanal da Serra Gaúcha em embalagem família!
          Aroma ligeiramente adocicado, corpo leve e refrescante, amargor perene 
          de lúpulos Alemães nobres. A cerveja clássica que carrega o espírito Sul-Riograndense.""",
        alcohol_content=5,
        brand="SUD",
        ibu=12,
        price=15,
        type=TypeEnum.chopp,
        disponible=True,
        source="http://127.0.0.1:8080/src/static/chopp_sud_500.png",
        quantity=10,
        volume=500,
    ),
    ProductIn(
        name="Chopp SUD IPA 1L",
        description="""A SUD IPA internacionalmente premiada em uma embalagem feita para dividir,
          como entendiam os criadores do estilo. Aroma intenso de abacaxi, toranja e resina 
          proveniente do blend de lúpulos americanos utilizado no Dry Hopping. Amargor marcante 
          mas redondo, faz essa cerveja impactante e extremamente bebível.""",
        price=17,
        brand="SUD",
        type=TypeEnum.chopp,
        alcohol_content=6.4,
        ibu=60,
        disponible=True,
        source="http://127.0.0.1:8080/src/static/chopp_sud_ipa_1L.png",
        quantity=100,
        volume=1000,
    ),
    ProductIn(
        name="Chopp Salva o Bairrista 1L",
        description="""O Bairrista é uma American Lager, de cor clara, amargor suave com baixa
          remanescência no paladar,
          de espuma persistente e aroma que remete a cereais e frutas. Cerveja com alto drinkability, 
          corpo leve e freshness marcante. .""",
        price=17.0,
        brand="Salva",
        type=TypeEnum.chopp,
        alcohol_content=4.3,
        ibu=10,
        disponible=True,
        source="http://127.0.0.1:8080/src/static/chopp_bairrista_1L.png",
        quantity=50,
        volume=1000,
    ),
        ProductIn(
        name="Chopp Wienbier 55 Pilsen Pet com 1,5L",
        description="""Chopp Pilsen artesanal em embalagem grande!""",
        price=19.0,
        brand="Wienbier",
        type=TypeEnum.chopp,
        alcohol_content=4.3,
        ibu=10,
        disponible=True,
        source="http://127.0.0.1:8080/src/static/chopp_wienbier_pilsen_1_5L.png",
        quantity=50,
        volume=1500,
    ),
      ProductIn(
        name="Chopp Stier Weiss Pet com 1,5L",
        description="""Chopp Weiss artesanal em embalagem grande. Feito com o melhor trigo do RS!""",
        price=21.0,
        brand="Stier",
        type=TypeEnum.chopp,
        alcohol_content=4.6,
        ibu=11,
        disponible=True,
        source="http://127.0.0.1:8080/src/static/chopp_stier_weiss_1_5L.png",
        quantity=50,
        volume=1500,
    ),
    ProductIn(
        name="Chopp Stier Red Ale Pet com 1L",
        description="""Chopp Red Ale artesanal em embalagem grande""",
        price=21.0,
        brand="Stier",
        type=TypeEnum.chopp,
        alcohol_content=4.3,
        ibu=16,
        disponible=True,
        source="http://127.0.0.1:8080/src/static/chopp_stier_red_ale_1L.png",
        quantity=50,
        volume=1000,
    ),
        ProductIn(
        name="Chopp Factory Pilsen Pet com 1L",
        description="""Chopp Pilsen artesanal em embalagem 1L""",
        price=21.0,
        brand="Factory",
        type=TypeEnum.chopp,
        alcohol_content=4.6,
        ibu=11,
        disponible=True,
        source="http://127.0.0.1:8080/src/static/chopp_factory_pilsen_1L.png",
        quantity=50,
        volume=1000,
    ),
]
