from src.models.product import ProductIn, TypeEnum

wines: list[ProductIn] = [
    ProductIn(
        name="Garrafão de Vinho Sangue de Boi Tinto",
        description="""O garrafao de vinho sangue de boi tinto suave 4000ml é o garrafao ideal para curtir bons momentos.""",
        alcohol_content=10,
        brand="Aurora",
        ibu=0,
        price=71.90,
        type=TypeEnum.wine,
        disponible=True,
        source="mudar imagem",
        quantity=100,
        volume=4000,
    ),
    ProductIn(
        name="Marques De Casa Concha Cabernet Sauvignon",
        description="""O Vinho Chileno MARQUES DE CASA CONCHA é um dos ícones da vinícola Concha y Toro. Tem como origem o Vale do Alto Maipo, no Chile, e é produzido com uvas Cabernet Sauvignon de vinhedos da região aos pés da Cordilheira dos Andes. De vermelho profundo, tem aroma de cereja, cedro, amora e um toque de alcatrão e fumaça, com notas amadeiradas""",
        alcohol_content=14.5,
        brand="Concha y Toro",
        ibu=0,
        price=118.89,
        type=TypeEnum.wine,
        disponible=True,
        source="mudar imagem",
        quantity=350,
        volume=750,
    ),
    ProductIn(
        name="Vinho Tinto Salton Paradoxo",
        description="""Vinho Tinto Salton Paradoxo Merlot Cabernet Franc e Marselan. Um blend de corpo médio, saboroso e com acidez equilibrada.""",
        alcohol_content=13.5,
        brand="Salton",
        ibu=0,
        price=65.00,
        type=TypeEnum.wines,
        disponible=True,
        source="mudar imagem",
        quantity=600,
        volume=750,
    ),
    ProductIn(
        name="Vinho Garibaldi Chardonnay",
        description="""Aromas que remetem a frutas tropicais como maracujá, abacaxi e nuances florais, com leve toque vegetal.""",
        alcohol_content=12.5,
        brand="Cooperativa Vinícola Garibaldi",
        ibu=0,
        price=50.00,
        type=TypeEnum.wines,
        disponible=True,
        source="mudar imagem",
        quantity=500,
        volume=750,
    ),
    ProductIn(
        name="Vinho Almadén Marselan",
        description="""Intenso e elegante, o Vinho Miolo Seleção Marselan revela o equilíbrio perfeito entre frutas em compota e especiarias, ideal para momentos especiais à mesa.""",
        alcohol_content=12,
        brand="Miolo",
        ibu=0,
        price=35.90,
        type=TypeEnum.wines,
        disponible=True,
        source="mudar imagem",
        quantity=500,
        volume=750,
    ),
    ProductIn(
        name="Kairós",
        description="""Densidade, complexidade e equilíbrio são as virtudes principais do corte deste vinho que foi elaborado seguindo os critérios das linhas Top Premium da vinícola, para o lançamento previsto após cinco anos em garrafa.""",
        alcohol_content=13.7,
        brand="Lidio Carraro",
        ibu=0,
        price=790.00,
        type=TypeEnum.wines,
        disponible=True,
        source="mudar imagem",
        quantity=50,
        volume=750,
    ),
    ProductIn(
        name="Vinho Tinto Gato Negro",
        description="""Elegante, frutado e versátil, o Vinho Gato Negro Malbec é uma ótima opção para quem valoriza um bom vinho, com tradição, originalidade e altíssima qualidade. Elaborado em renomadas vinícolas chilenas, com terroirs férteis de clima ideal, é um tinto levemente encorpado, com tons violáceos, que apresenta sabores ressaltados de groselha, cereja e toques de especiarias, conquistando reconhecimento no Chile e no exterior, gerando um paladar fresco e macio.""",
        alcohol_content=12.1,
        brand="San Pedro",
        ibu=0,
        price=41.90,
        type=TypeEnum.wines,
        disponible=True,
        source="mudar imagem",
        quantity=490,
        volume=750,
    ),
    ProductIn(
        name="Gran Pinot Noir",
        description="""Durante 18 meses, repousa em barricas, onde o sutil eco dos cantos gregorianos permeia o ambiente, criando micro-ondulações que transformam cada gota em uma experiência sensorial única. Este contato divino entre o vinho e a madeira confere camadas complexas de aromas e sabores, que evoluem com delicadeza ao longo do tempo. Após o envasamento, descansa por mais 30 meses em cave, atingindo um equilíbrio sublime.""",
        alcohol_content=14,
        brand="Valduga",
        ibu=0,
        price=250.00,
        type=TypeEnum.wines,
        disponible=True,
        source="mudar imagem",
        quantity=420,
        volume=750,
    ),
]
