from src.database import static_files_source
from src.models.product import ProductIn, TypeEnum

# doing ..
sparklings: list[ProductIn] = [
    ProductIn(
        name="Espumante Aurora Pinto Bandeira Extra Brut",
        description="""O espumante Aurora Pinto Bandeira Extra Brut é feito com o corte perfeito entre Chardonnay, Pinot Noir e Riesling Itálico, harmonizando o clássico com o inovador. Esse corte proporcionara uma bebida única, de coloração amarelo palha e cremosidade singular. Após amadurecer por 12 meses em contato com as leveduras, esse espumante possui aromas que remetem à doçura de damascos e a robustez  de amêndoas tostadas. Toques elegantes de flores como a laranjeira se destacam, acompanhando seu paladar de delicada acidez. Este espumante é elaborado pelo método tradicional, em um terroir mundialmente reconhecido com I.P Altos de Pinto Bandeira.""",
        alcohol_content=13,
        brand="Aurora",
        ibu=0.0,
        price=100,
        type=TypeEnum.sparkling,
        disponible=True,
        source=f"{static_files_source}/sparkling_aurora_pinto_bandeira.png",
        quantity=10,
        volume=750,
    ),
    ProductIn(
        name="Cave Amadeu Brut",
        description="""O espumante Cave Geisse Brut feito em Pinto Bandeira, segundo o método tradicional""",
        alcohol_content=12,
        brand="Cave Geisse",
        ibu=0.0,
        price=99,
        type=TypeEnum.sparkling,
        disponible=True,
        source=f"{static_files_source}/sparkling_cave_amadeu_brut.png",
        quantity=10,
        volume=750,
    ),
    ProductIn(
        name="Privilege Espumante Brut",
        description="""Espumante elaborado pelo método tradicional, com autólise de 18 meses.""",
        alcohol_content=12,
        brand="Peterlongo",
        ibu=0.0,
        price=110,
        type=TypeEnum.sparkling,
        disponible=True,
        source=f"{static_files_source}/sparkling_privilege_espumante_brut_750ml.png",
        quantity=10,
        volume=750,
    ),
    ProductIn(
        name="Chandon Excellence Brut",
        description="""Um espumante excepcional dominado pelo Pinot Noir que ganhou complexidade aromática pelo longo amadurecimento sobre leveduras. Seu aroma lembra cítricos cristalizados, ameixa preta, amêndoas frescas e torradas, especiarias doces como canela, cravo e caramelo, e pão tostado. O paladar começa por um franco ataque de acidez, continua amplo e macio e termina com um final persistente de frutas secas e toques de torrefação.""",
        alcohol_content=12,
        brand="Cave Geisse",
        ibu=0.0,
        price=110,
        type=TypeEnum.sparkling,
        disponible=True,
        source=f"{static_files_source}/sparkling_chandon_excellence_brut.png",
        quantity=10,
        volume=750,
    ),
    ProductIn(
        name="Espumante Salton Moscatel 750ml",
        description="""Espumante Salton Moscatel. A combinação perfeita para acompanhar doces e frutas, com aromas essencialmente frutados e florais. Compre agora na Loja da Salton!""",
        alcohol_content=7.5,
        brand="Salton",
        ibu=0.0,
        price=39.9,
        type=TypeEnum.sparkling,
        disponible=True,
        source=f"{static_files_source}/sparkling_espumante_salton_moscatel_750ml.png",
        quantity=10,
        volume=750,
    ),
    ProductIn(
        name="Espumante Miolo Cuvée Tradition Brut Rosé 1500ml",
        description="""Excelente como aperitivo, harmoniza com comida leve, saladas de folhas, frutos do mar, peixes, massas e pizzas vegetarianas.""",
        alcohol_content=12.5,
        brand="Miolo",
        ibu=0.0,
        price=103.93,
        type=TypeEnum.sparkling,
        disponible=True,
        source=f"{static_files_source}/sparkling_espumante_miolo_cuvee_tradition_brut_rose_1500ml.png",
        quantity=10,
        volume=1500,
    ),
    ProductIn(
        name="Espumante Brut D.O. - 750ML",
        description="""Elaborado apenas com uvas da variedade Chardonnay (Blanc de Blancs) pelo Método Tradicional, cuja segunda fermentação ocorre na própria garrafa. Possui maturação de 36 meses com as leveduras, o que proporciona a este produto excelente cremosidade e persistência além de uma complexidade aromática que lembra manteiga, nozes e mel.""",
        alcohol_content=12.5,
        brand="Cave de Pedra",
        ibu=0.0,
        price=250,
        type=TypeEnum.sparkling,
        disponible=True,
        source=f"{static_files_source}/sparkling_espumante_brut_DO_750ml.png",
        quantity=10,
        volume=750,
    ),
]
