from src.database import static_files_source
from src.models.product import ProductIn, TypeEnum

whiskeys: list[ProductIn] = [
    ProductIn(
        name="Whiskey Jack Daniels 1L",
        description="""Este Tennessee Whiskey, repousado nos barris centrais da destilaria, oferece um sabor suave e marcante de madeira, com notas adocicadas e de baunilha. Ideal para consumir puro, com gelo, ou em drinks como Jack & Cola e Jack & Citrus.""",
        alcohol_content=40,
        brand="Jack Daniels",
        ibu=0.0,
        price=189.99,
        type=TypeEnum.whiskey,
        disponible=True,
        source=f"{static_files_source}/whiskey_jack_daniel_1L.png",
        quantity=20,
        volume=1000,
    ),
    ProductIn(
        name="Whisky Grand Old Parr 12 Anos 750ml",
        description="""Grand Old Parr, criado em 1871 para homenagear o lendário Thomas Parr, é um whisky escocês envelhecido por 12 anos. Com o renomado malte Cragganmore de Speyside, oferece a promessa de longevidade em cada dose.""",
        alcohol_content=40,
        brand="Old Parr",
        ibu=0.0,
        price=149.99,
        type=TypeEnum.whiskey,
        disponible=True,
        source=f"{static_files_source}/whiskey_old_parr_750ml.png",
        quantity=20,
        volume=750,
    ),
    ProductIn(
        name="Whisky Buchanans 12 anos 1L",
        description="""Whisky Buchanan's 12 Anos 1 Litro. Whisky escocês. James Buchanan's quis fazer um scotch whisky para oferecer aos seus melhores amigos. Em 1879, vivendo em Londres, começou a buscar por uma mistura que tivesse tanto qualidade quanto um sabor inconfundível. Em 1884, ele tinha criado um blend que ia ao encontro de seu desejo e como garantia de excepcional qualidade desse produto, colocou seu próprio nome nele. Cada single malt da composição de Buchanan's 12 anos tem aromas e sabores diferentes e, quando misturados pelo master blender - profissional que prepara, no faro, a bebida - transformam-se em sabores diferentes, que dão identidade ao whisky, como em Buchanan's 12 anos. Graduação alcoólica 40% vol. - Conteúdo 1000 ml (vidro). Whisky importado da Escócia.""",
        alcohol_content=40,
        brand="Buchanans",
        ibu=0.0,
        price=231.99,
        type=TypeEnum.whiskey,
        disponible=True,
        source=f"{static_files_source}/whiskey_buchanans_750ml.png",
        quantity=20,
        volume=750,
    ),
    ProductIn(
        name="Whisky Johnnie Walker Gold Label Reserve 750ml",
        description="""O Johnnie Walker Gold Label Reserve é um blended whisky escocês de luxo que é composto a partir de uma combinação de diferentes whiskies de malte e grãos de várias destilarias da Escócia.""",
        alcohol_content=40,
        brand="Johnnie Walker",
        ibu=0.0,
        price=349.99,
        type=TypeEnum.whiskey,
        disponible=True,
        source=f"{static_files_source}/whiskey_johnnie_walker_gold_label_750ml.png",
        quantity=20,
        volume=750,
    ),
    ProductIn(
        name="Whiskey Bulleit Bourbon 750ml",
        description="""Whiskey robusto, no paladar apresente notas picantes e sabor residual leve. Produzido com água pura filtrada em calcário e repousado em barris de carvalho americano carbonizados, seguindo a tradição da família Bulleit.""",
        alcohol_content=45,
        brand="Bulleit Bourbon",
        ibu=0.0,
        price=262.99,
        type=TypeEnum.whiskey,
        disponible=True,
        source=f"{static_files_source}/whiskey_bulleit_bourbon_750ml.png",
        quantity=20,
        volume=750,
    ),
    ProductIn(
        name="Whisky Royal Salute 21 Anos The Malts Blend Escocês 700ml",
        description="""Composto por mais de 21 single malts maturados por, no mínimo, 21 anos, oferecendo uma experiência rica e profunda. Seu sabor combina notas frutadas, florais e especiarias, com um final longo, doce e picante.""",
        alcohol_content=40,
        brand="Royal Salute",
        ibu=0.0,
        price=899.99,
        type=TypeEnum.whiskey,
        disponible=True,
        source=f"{static_files_source}/whiskey_royal_salute_750ml.png",
        quantity=20,
        volume=750,
    ),
    ProductIn(
        name="Whisky Chivas Regal Extra 13 anos Escocês 750ml",
        description="""Um blended scotch whisky envelhecido por pelo menos 13 anos e seletivamente envelhecido em barris de vinho espanhol Jerez Oloroso, Chivas 13 Anos imprime em seu líquido uma enorme riqueza e complexidade de sabores.""",
        alcohol_content=40,
        brand="Chivas Regal",
        ibu=0.0,
        price=190.99,
        type=TypeEnum.whiskey,
        disponible=True,
        source=f"{static_files_source}/whiskey_chivas_regal_750ml.png",
        quantity=20,
        volume=750,
    ),
]
